name: Add comment
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == "help wanted"
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue comment "$NUMBER" --body "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            This is availabele to work 
            bye bey
